db:
  COUCHDB_SERVER: 'http://docker:5984'
  COUCHDB_DATABASE: 'barfight'
  COUCHDB_DATABASE_REVIEW: 'to_review'
foursquare:
  CLIENT_ID: 'WE0OIWTHQSXE20QEUOJVYZDSES21NJTJO3VLBLH4ZUN0I5SQ'
  CLIENT_SECRET: 'CWUNQR1OINKSOG42RMIUR3OWKEV1E4PEX3ZJ0QWTKRQYXMID'
  API_VERSION: 20150318
brewerydb:
  API_KEY: '52df05bdc21e3e3383580d603959aad6'
  BASE_URL: 'http://api.brewerydb.com/v2'
